name: Fullstack Deploy (SPA + Spring) to Azure App Service

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Build frontend
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # Copy frontend build into backend resources
      - name: Copy frontend to backend
        run: |
          rm -rf backend/src/main/resources/static/*
          mkdir -p backend/src/main/resources/static
          cp -r frontend/dist/* backend/src/main/resources/static/

      # Build backend with Maven
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        working-directory: backend
        run: mvn -B -DskipTests package

      - name: Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: backend/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_FULL }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISH_PROFILE_FULL }}
          package: '*.jar'
